### PR TITLE
Update SDCLI Version

### PR DESCRIPTION
**Pull request by sydneyteh96**

### CODE REVIEW

**Review by akhalina — DISMISSED** [review]

**Comment by gcase555** [comment]
I think we should upgrade our go version here as well https://github.com/asecurityteam/awsconfig-transformerd/blob/master/go.mod#L3 since the latest sdcli uses golang 1.16

**Review by gcase555 — CHANGES_REQUESTED** [review]
should we upgrade to the latest go as well?

**Review by ensary — APPROVED** [review]

**Comment by sydneyteh96** [comment]
> should we upgrade to the latest go as well?

**Review by gcase555 — APPROVED** [review]
+1

We'll want to test this out in adev once we pull it into our service in bitbucket.

**Review by alecbert-atl — APPROVED** [review]

**Pull request merged**
